"""app_table_add_review_field

Revision ID: 075ae41d280e
Revises: 7e001c5a6df3
Create Date: 2024-08-31 02:24:11.473104

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '075ae41d280e'
down_revision = '7e001c5a6df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracing_app_configs')
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', models.StringUUID(), nullable=True))
        batch_op.add_column(sa.Column('review_status', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('review_remark', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('review_remark')
        batch_op.drop_column('review_status')
        batch_op.drop_column('user_id')

    op.create_table('tracing_app_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('app_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tracing_provider', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tracing_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tracing_app_config_pkey')
    )
    # ### end Alembic commands ###
