"""empty message

Revision ID: 3184661b766d
Revises: 408176b91ad3
Create Date: 2024-07-28 22:25:53.138695

"""
from alembic import op
import models as models
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3184661b766d'
down_revision = '408176b91ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('embedding_vector_index_56f61607_dea9_4594_9fd4_5ba23b703209_nod')
    #op.drop_table('embedding_vector_index_a7eb1e0d_663f_46ce_ab17_9736ebd5f856_nod')
    #op.drop_table('tracing_app_configs')
    #op.drop_table('embedding_vector_index_a5bbac5f_cc5e_45eb_afc4_07821e6f2ccb_nod')
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover', sa.String(length=500), server_default=sa.text("''::character varying"), nullable=False))

    with op.batch_alter_table('dataset_permissions', schema=None) as batch_op:
        batch_op.create_index('idx_dataset_permissions_tenant_id', ['tenant_id'], unique=False)

    with op.batch_alter_table('trace_app_config', schema=None) as batch_op:
        batch_op.drop_index('trace_app_config_app_id_idx')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trace_app_config', schema=None) as batch_op:
        batch_op.create_index('trace_app_config_app_id_idx', ['app_id'], unique=False)

    with op.batch_alter_table('dataset_permissions', schema=None) as batch_op:
        batch_op.drop_index('idx_dataset_permissions_tenant_id')

    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('cover')

    op.create_table('embedding_vector_index_a5bbac5f_cc5e_45eb_afc4_07821e6f2ccb_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_a5bbac5f_cc5e_45eb_afc4_07821e6f2cc_pkey')
    )
    op.create_table('tracing_app_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('app_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tracing_provider', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tracing_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tracing_app_config_pkey')
    )
    op.create_table('embedding_vector_index_a7eb1e0d_663f_46ce_ab17_9736ebd5f856_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_a7eb1e0d_663f_46ce_ab17_9736ebd5f85_pkey')
    )
    op.create_table('embedding_vector_index_56f61607_dea9_4594_9fd4_5ba23b703209_nod',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='embedding_vector_index_56f61607_dea9_4594_9fd4_5ba23b70320_pkey')
    )
    # ### end Alembic commands ###
