"""empty message

Revision ID: 3bc5249531aa
Revises: ecd2f7a3c35f
Create Date: 2024-08-01 07:50:17.466591

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc5249531aa'
down_revision = 'ecd2f7a3c35f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=500), server_default=sa.text("''::character varying"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('website')

    # ### end Alembic commands ###
