"""empty message

Revision ID: 45e737ac7f70
Revises: 3184661b766d
Create Date: 2024-07-29 03:43:03.137130

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e737ac7f70'
down_revision = '3184661b766d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('open_times', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('open_times')
        batch_op.drop_column('score')

    # ### end Alembic commands ###
