"""empty message

Revision ID: 6092510d8164
Revises: 3bc5249531aa
Create Date: 2024-08-04 11:29:53.700576

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6092510d8164'
down_revision = '3bc5249531aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_status', sa.String(length=50), server_default=sa.text("''::character varying"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('llm_status')

    # ### end Alembic commands ###
