"""empty message

Revision ID: ecd2f7a3c35f
Revises: 45e737ac7f70
Create Date: 2024-07-30 04:47:51.727027

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd2f7a3c35f'
down_revision = '45e737ac7f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pass_condition', sa.String(length=1000), server_default=sa.text("''::character varying"), nullable=False))
        batch_op.add_column(sa.Column('pass_type', sa.String(length=50), server_default=sa.text("'count'::character varying"), nullable=False))
        batch_op.add_column(sa.Column('pass_config', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('pass_config')
        batch_op.drop_column('pass_type')
        batch_op.drop_column('pass_condition')

    # ### end Alembic commands ###
